project_id = "blualert"

[auth]
enable_signup = true
enable_anonymous_sign_ins = false
site_url = "http://localhost:3000"
additional_redirect_urls = []

[auth.email]
enable_signup = true
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[functions.occurrence-session]
verify_jwt = true

[functions.occurrence-confirm]
verify_jwt = true

[functions.remote-config]
verify_jwt = false

[functions.situation]
verify_jwt = false

[functions.escalate-queue]
verify_jwt = false
